### ISSUE TITLE
Grand ToDo List;

### ISSUE THREAD

**Issue by melony-cmd** [melony-cmd/fsuae-3.1.66#1]
- [x] remove some hacks in sdl.c
- [x] add configuration option for borderless window.
- [x] add option to skip adding to task bar.
- [ ] find a way to 'force' window to bottom/to top of the zorder.
- [ ] find a way for workbench to adjust its window zorder.
- [ ] finish off fsuae bin tools, still plenty to do, some seem hidden at least from uaectrl & uae-control, seem some stuff was implemented but not given a tool amiga side to use it? Or maybe I've not found it yet.
- [ ] find out what rcli is actually supposed to do.
- [x] add window always on top
- [ ] add / look for switch that disables the screensaver.

....

**Comment by melony-cmd** [comment]
borderless window was always apart of .fs-uae purview.

**Comment by melony-cmd** [comment]
add;
window_skip_taskbar = 0
to .fs-uae configuration file to remove the window from the task bar.
